"""followers

Revision ID: 11e327e08182
Revises: 62e2dce64574
Create Date: 2021-05-15 17:02:04.065219

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '11e327e08182'
down_revision = '62e2dce64574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followrs',
                    sa.Column('follower_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followrs')
    # ### end Alembic commands ###
