"""new fields in user model

Revision ID: 62e2dce64574
Revises: 6af52f489dbb
Create Date: 2021-03-02 00:20:17.808302

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '62e2dce64574'
down_revision = '6af52f489dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
